### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by mvndaai** [randy3k/remote-atom#13]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate ($HOME/.atom/packages/remote-atom/lib/remote-atom.coffee:121:13)
```

**Comment by randy3k** [comment]
I thought it was fixed after the recent commits.

**Comment by mvndaai** [comment]
I did some updates today, maybe I had the warning left over. I will close this ticket, unless it comes back. Thanks for working on it.

**Comment by randy3k** [comment]
Thanks. I hope you find this package useful.
