### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by psawaya** [randy3k/remote-atom#15]
Atom.app created this automatically. Hope this is useful:

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/psawaya/.atom/packages/remote-atom/lib/remote-atom.coffee:121:13)
```

**Comment by randy3k** [comment]
Are you using the latest atom and remote-atom?

**Comment by randy3k** [comment]
I think it should be closed given the recent commits.
