### ISSUE TITLE
remote-atom "Unable to start Server" Linux RPM

### ISSUE THREAD

**Issue by blastdan** [randy3k/remote-atom#16]
Remote-atom will not start server on a Fedora 21 installation. Console only spits out "unable to start server"

I have tried running Atom as root with the same results. 
Installed Nodejs as well with same results.

Any idea what could be causing this?

Thanks.

**Comment by randy3k** [comment]
Did you open another atom window? or using rmate client in another editor, for example, sublime text?

**Comment by blastdan** [comment]
Only one instance of Atom was opened, and no other text editors were being used.You may consider adding the exception message to the console log when this fails to get a better idea of what caused the server to fail starting.

**Comment by randy3k** [comment]
I have no problems on Mac, let me check the linux part later.

**Comment by randy3k** [comment]
I also got no errors on Ubuntu 14.04.1

**Comment by blastdan** [comment]
Interesting. I'll try it again on a debian build.
is this normally a cause of the port being busy?

**Comment by randy3k** [comment]
You may want to try to change to other ports in the settings.

**Comment by blastdan** [comment]
On another Fedora box I was able to start a server. Not sure what the issue was on the other box.

**Comment by randy3k** [comment]
most probably the default port was being used by other programs.
