### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by throker** [randy3k/remote-atom#17]
I got the latest version of both Atom and Remote-Atom installed. You can see a screenshot below. It does still work though.
![remote-atom deprication](https://cloud.githubusercontent.com/assets/5545766/7480743/a92d2a56-f338-11e4-8f25-ecea86dc4ce6.png)

Below is the automated issue text created by Atom
------------------------------
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:247:11)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
```

**Comment by randy3k** [comment]
I am quite busy these two days. Could you submit a PR? Thanks in advance.

**Comment by randy3k** [comment]
Fixed now.

**Comment by throker** [comment]
Thanks randy3k! I don't think I would have been much help since I'm very new to Git. And I also only discovered/installed Atom 2 days ago. I've installed the update and it works fine without any issues.

**Comment by randy3k** [comment]
It is quite annoying that the atom API changes frequently. 
😅
