### ISSUE TITLE
Tree View

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [randy3k/remote-atom#26]
Would it be possible to (or are there plans to) integrate this with the tree view that comes with atom? The current file browser is *not* very intuitive...

**Comment by randy3k** [comment]
Remote-atom edits remote file while tree view is used to browse local file. They are very different tools, how do you want remote-atom to integrate Tree view??

**Comment by The-Penultimate-Defenestrator** [comment]
They're both file browsers. Tree-view is much more intuitive. I'd like a file browser that is **like** tree view, but for remote atom. What's not clear?

**Comment by randy3k** [comment]
Remote atom is not a file browser...do you meant "remote edit"? It is the repo for "remote atom".
