### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by tristannederhoff** [randy3k/remote-atom#32]
Can't work with multiple users at the same time. 

If my somebody else is logged in and creates a new file on a server it also opens in my atom editor. Working on same server, different users and different (Magento) installations.

**Comment by randy3k** [comment]
It is a limitation of the `rmate` protocol, but a thing remote-atom is able to address.

https://github.com/textmate/rmate/issues/15
https://github.com/textmate/rmate/issues/32

**Comment by randy3k** [comment]
aha....it looks like `rmate` now support Unix Socket: https://github.com/textmate/rmate/pull/38/commits

Supporting Unix sockets should handle multiple users problem.

**Comment by randy3k** [comment]
Let me

**Comment by randy3k** [comment]
Bash version of rmate recently also gained unix socket support: https://github.com/aurora/rmate/pull/63

**Comment by drscotthawley** [comment]
How does one go about creating a ~/.rmate.socket file, or is there a sample file around?  Been searching for info on the interwebs, can't find anything appropriate.
