### ISSUE TITLE
Garbled and truncated files are saved

### ISSUE THREAD

**Issue by cecn** [randy3k/remote-atom#36]
Working with Atom 1.11.2 on OSX 10.9.5, just installed remote-atom to give it a go. Remote server is ubuntu 14.04 with rmate C version compiled locally.
Opening files works a charm, no issue at all, but saving them back inserts some garbled binary stuff in the middle (sometimes at the top) and truncates the file being saved.
As I need to get stuff done I've given up before I tried to debug but I'll be glad to help if this isn't an issue that's unique to me. I'll also test on other system once I get the time.

**Comment by randy3k** [comment]
Personally, I use the bash version and I have never used / tested the c version rmate. Could you try to switch the the office ruby / the bash version of rmate?

**Comment by cecn** [comment]
I was under the impression that saving was done without any intervention from rmate (using scp/sftp over the reverse ssh tunnel) so I never considered rmate being the culprit... obviously I was wrong, the bash version seems to work just fine.
That's that, I guess... thanks!
